version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    tty: true
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
      WEB_HOST: ${WEB_HOST}
      WEB_PROTOCOL: ${WEB_PROTOCOL}
      MAIL_BCC: ${MAIL_BCC}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_PASSWD: ${SMTP_PASSWD}
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_SECRET_KEY: ${TWITTER_API_SECRET_KEY}
      FACEBOOK_API_KEY: ${FACEBOOK_API_KEY}
      FACEBOOK_API_SECRET_KEY: ${FACEBOOK_API_SECRET_KEY}
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets: